title: Medical Video AI Assessment and Uncertainty Quantification - Bridging Research and Practice
description: The workshop aims to introduce regulatory science on AI-enabled devices to the ISBI community, with a particular focus on the assessment of medical video AI and uncertainty quantification. 

url: https://FengYang-FDA2023.github.io/2026ISBIWorkshop-VideoAIAsssessmentandUncertaintyQuantification-1st
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /home #index.html
    - title: About
      url: /about
    - title: Call for paper
      url: /paper
    - title: Keynote speakers
      url: /keynote
    - title: Schedule
      url: /schedule

# social:
    # github: brianmaierjr
    # twitter: brianmaierjr
    # facebook: brianmaierjr
    # email: brimaidesigns@gmail.com
    # linkedin: brianmaierjr
    # youtube: RickAstleyYT
    # tumblr: i-am-a-fish

# google_analytics: "UA-58263416-1"

# disqus:
    # shortname: brianmaierjr
